<?php

return [
    'conditions' => [
        'D' => "Desplazado/a",
        'MCH' => "Mujer cabeza de hogar",
        'CI' => "Victima del conflicto interno",
        'OH' => "Otros hechos",
        'NA' => "No aplica",
    ],
    'disability_types' => [
        'F' => 'Física',
        'V' => 'Visual',
        'A' => 'Auditiva',
        'C' => 'Cognitiva',
        'M' => 'Mental',
        'MUL' => 'Múltiple',
        'O' => 'Otra, cual?',
    ],
    'educational_levels' => [
        'PREE' => 'Preescolar',
        'PRI' => 'Primaria',
        'BAC' => 'Bachillerato',
        'TEC' => 'Técnico',
        'TECN' => 'Tecnólogo',
        'PRE' => 'Pregrado',
        'POS' => 'Posgrado',
        'N' => 'Ninguno',
    ],
    'ethnicities' => [
        'AFRO' => 'Afrodescendiente',
        'IND' => 'Indígena',
        'ROM' => 'ROM(Gitana)',
        'PAL' => 'Palenquero',
        'RAI' => 'Raizal',
        'NEG' => 'Negro',
        'N' => 'Ninguno',
    ],
    'genders' => [
        'M' => 'Masculino',
        'F' => 'Femenino',
        'LGBTIQ+' => 'LGBTIQ+',
        'O' =>  'Otro',
    ],
    'health_conditions' => [
        'B' => 'Bueno',
        'R' => 'Regular',
        'M' => 'Malo',
    ],
    'lineaments' => [
        'DC' => 'Diálogo cultural',
        'EF' => 'Enfoque diferencial',
        'AD' => 'Acción sin daño',
        'CEP' => 'Cultura como entorno protector',
        'EP' => 'Ecosistema de paz',
    ],
    'linkage_projects' => [
        'PMIE' => 'Por medio de una Institución educativa',
        'PMEPUB' => 'Por medio de una Entidad pública',
        'PMEPRI' => 'Por medio de una Entidad privada',
        'PMGCP' => 'Por medio de un gestor cultural del proyecto',
        'PMMCP' => 'Por medio de un monitor cultural del proyecto',
        'PMR' => 'Por medio de un referido',
    ],
    'medical_services' => [
        'S' => 'Subsidiado',
        'C' => 'Contributivo',
    ],
    'participant_types' => [
        'C' => 'Caracterizado',
        'NC' => 'No caracterizado',
    ],
    'decisions' => [
        '1' => 'Si',
        '0' => 'No',
    ],
    'relatives' => [
        'M' => 'Mamá',
        'P' => 'Papá',
        'T' => 'Tio(a)',
        'PR' => 'Primo(a)',
        'H' => 'Hermano(a)',
        'A' => 'Abuelo(a)',
    ],
    'stratums' => [
        1 => '1',
        2 => '2',
        3 => '3',
        4 => '4',
        5 => '5',
        6 => '6',
    ],
    'type_documents' => [
        'RC' => 'Registro civil',
        'TI' => 'Tarjeta de identidad',
        'CC' => 'Cédula de ciudadania',
    ],
    'zones' => [
        'R' => 'Rural',
        'U' => 'Urbano',
    ],
    'status' => [
        'REC' => 'RECHAZADO',
        'REV' => 'REVISADO',
        'ENREV' => 'EN REVISIÓN',
        'APRO' => 'APROBADO',
    ],
    'binnacles' => [
        'JP' => 'JORNADA PACTO',
        'SC' => 'SEMILLERO CULTURAL',
        'AC' => 'ACTIVACIÓN CULTURAL',
        'TP' => 'TAPETE METODOLÓGICO',
        'EC' => 'ENSAMBLE CULTURAL',
    ],
    'place_types' => [
        'F' => 'FUNDACIÓN',
        'P' => 'PARQUE',
        'SC' => 'SALÓN COMUNAL',
        'CEC' => 'COLEGIO EN CONTRAJORNADA',
        'O' => 'OTRO',
    ],
    'activation_mode' => [
        'virtual' => 'Virtual',
        'presencial' => 'Presencial',
    ],

    'disease_types' => [
        'CV' => 'Cardiovascular',
        'R' => 'Respiratorio',
        'OM' => 'Osteomuscular',
        'N' => 'Neurológica',
        'O' => 'Otra, cual?',
    ],
    'marital_status' => [
        'CV' => 'Soltero',
        'R' => 'Casado',
        'UL' => 'Unión libre',
        'D' => 'Divorciado',
        'V' => 'Viudo',
    ],
    'relationship_households' => [
        'E' => 'Esposo(a)',
        'H' => 'Hijo(a)',
        'JH' => 'Jefe de hogar',
        'F' => 'Familiar',
    ],
    'single_registry_victims' => [
        'S' => 'Si',
        'N' => 'No',
        'NS' => 'No sabe',
        'NA' => 'No aplica',
    ],
    'type_diseases' => [
        'I' => 'Infecciosa',
        'M' => 'Mentales',
        'R' => 'Respiratorias',
        'C' => 'Circulatorias',
        'S' => 'Sanguineas',
        'N' => 'Nutricionales',
        'E' => 'Endocrinas',
    ],
    'beneficiary_attrition_factors' => [
        'PF' => 'Problemas familiares',
        'PE' => 'Problemas económicos',
        'FT' => 'Falta de tiempo',
        'OTRO' => 'Otro ¿cual?',
    ],
    'relationships' => [
        'P' => 'Papá',
        'M' => 'Mamá',
        'PA' => 'Padrastro',
        'MA' => 'Madrastra',
        'T' => 'Tio (a)',
        'PR' => 'Primo (a)',
        'H' => 'Hermano (a)',
        'A' => 'Abuelo (a)',
        'O' => 'Otro',
    ],
    'values' => [
        'C' => 'Convivencia',
        'S' => 'Solidaridad',
        'R' => 'Respeto a los derechos humanos',
        'I' => 'Interculturalidad',
        'P' => 'Pluralidad',
    ],
    'filter_level' => [
        'R' => 'Representativo',
        'C' => 'Iniciación',
        'SF' => 'Semillero Formación',
        'ST' => 'Semillero Transición',
    ],
    'activity_type' => [
        'C' => 'Circulación',
        'E' => 'Ensamble',
        'SC' => 'Semillero cultural',
    ],
    'strengthening_types' => [
        'FPAM' => 'Fortalecimiento pedagógico al equipo de apoyo metodológico',
        'IMFG' => 'Instrucción metodológica, fortalecimiento a gestores',
        'FEAR' => 'Fortalecimiento especificado a roles',
        'SEOE' => 'Socialización de la estrategia a otros equipos (cambios metodología, pedagogía, roles, nuevas tendencias)',
    ],
    'aspects' => [
        'PTGEP' => 'Plan de trabajo de gestores enviado previamente',
        'SDSCL' => 'Solicitudes de direccion,subdireccion,coordinaciones,lideres',
        'RP' => 'Reportes de plataforma (-/+)',
        'AAP' => 'Autonomía del apoyo pedagogico',
    ],
    'evaluate_aspects' => [
        'PA' => 'Proyección artística',
        'T' => 'Técnica',
        'C' => 'Comportamiento',
    ]
];
